// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Logo Soup → brands*
 */
export interface LogoSoupDocumentDataBrandsItem {
  /**
   * name field in *Logo Soup → brands*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_soup.brands[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * services field in *Logo Soup → brands*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_soup.brands[].services
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  services: prismic.KeyTextField;

  /**
   * logo color field in *Logo Soup → brands*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_soup.brands[].logo_color
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_color: prismic.ImageField<never>;

  /**
   * logo negative field in *Logo Soup → brands*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_soup.brands[].logo_negative
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_negative: prismic.ImageField<never>;

  /**
   * active background field in *Logo Soup → brands*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_soup.brands[].active_background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  active_background: prismic.ImageField<never>;

  /**
   * active background mobile crop field in *Logo Soup → brands*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_soup.brands[].active_background_mobile_crop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  active_background_mobile_crop: prismic.ImageField<never>;

  /**
   * project link field in *Logo Soup → brands*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_soup.brands[].project_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * isFeatured field in *Logo Soup → brands*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: logo_soup.brands[].isFeatured
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isFeatured: prismic.BooleanField;
}

/**
 * Content for Logo Soup documents
 */
interface LogoSoupDocumentData {
  /**
   * brands field in *Logo Soup*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_soup.brands[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  brands: prismic.GroupField<Simplify<LogoSoupDocumentDataBrandsItem>>;
}

/**
 * Logo Soup document from Prismic
 *
 * - **API ID**: `logo_soup`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LogoSoupDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LogoSoupDocumentData>,
    "logo_soup",
    Lang
  >;

type PageDocumentDataSlicesSlice = RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ProjectDocumentDataSlicesSlice =
  | ScreenWidthColumnsSlice
  | SlideshowSlice
  | ValueBlockSlice
  | ScreenWidthImageSlice
  | ContentWidthImageSlice
  | RichTextSlice;

/**
 * Content for project documents
 */
interface ProjectDocumentData {
  /**
   * title field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * hero field in *project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.hero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero: prismic.ImageField<never>;

  /**
   * tagline field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * branding field in *project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.branding
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  branding: prismic.BooleanField;

  /**
   * product field in *project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.product
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  product: prismic.BooleanField;

  /**
   * print field in *project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.print
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  print: prismic.BooleanField;

  /**
   * environmental field in *project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.environmental
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  environmental: prismic.BooleanField;

  /**
   * packaging field in *project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.packaging
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  packaging: prismic.BooleanField;

  /**
   * digital field in *project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.digital
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  digital: prismic.BooleanField;

  /**
   * manually set related project one field in *project*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.relatedprojectoverride1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  relatedprojectoverride1: prismic.ContentRelationshipField<"project">;

  /**
   * manually set related project two field in *project*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.relatedprojectoverride2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  relatedprojectoverride2: prismic.ContentRelationshipField<"project">;

  /**
   * Slice Zone field in *project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice> /**
   * Meta Title field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * featured image field in *project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.featured_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;
}

/**
 * project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

/**
 * Item in *showcase → projects*
 */
export interface ShowcaseDocumentDataProjectsItem {
  /**
   * project field in *showcase → projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.projects[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;

  /**
   * set image field in *showcase → projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.projects[].imageOverride
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageOverride: prismic.ImageField<never>;

  /**
   * set title field in *showcase → projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: optional
   * - **API ID Path**: showcase.projects[].titleOverride
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleOverride: prismic.KeyTextField;

  /**
   * set subtitle field in *showcase → projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: optional
   * - **API ID Path**: showcase.projects[].subtitleOverride
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitleOverride: prismic.KeyTextField;
}

type ShowcaseDocumentDataSlicesSlice =
  | ValueBlockSlice
  | SlideshowSlice
  | ScreenWidthColumnsSlice
  | ContentWidthImageSlice
  | ScreenWidthImageSlice
  | RichTextSlice;

type ShowcaseDocumentDataSlices1Slice = never;

/**
 * Content for showcase documents
 */
interface ShowcaseDocumentData {
  /**
   * title field in *showcase*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * tagline field in *showcase*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * hero field in *showcase*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.hero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero: prismic.ImageField<never>;

  /**
   * body field in *showcase*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * featuredProject field in *showcase*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.featuredproject
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  featuredproject: prismic.ContentRelationshipField<"project">;

  /**
   * set featured image field in *showcase*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.featuredImageOverride
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featuredImageOverride: prismic.ImageField<never>;

  /**
   * set featured title field in *showcase*
   *
   * - **Field Type**: Text
   * - **Placeholder**: optional
   * - **API ID Path**: showcase.featuredTitleOverride
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  featuredTitleOverride: prismic.KeyTextField;

  /**
   * set featured subtitle title field in *showcase*
   *
   * - **Field Type**: Text
   * - **Placeholder**: optional
   * - **API ID Path**: showcase.featuredSubtitleOverride
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  featuredSubtitleOverride: prismic.KeyTextField;

  /**
   * projects field in *showcase*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.projects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projects: prismic.GroupField<Simplify<ShowcaseDocumentDataProjectsItem>>;

  /**
   * Slice Zone field in *showcase*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ShowcaseDocumentDataSlicesSlice> /**
   * Meta Title field in *showcase*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: showcase.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *showcase*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: showcase.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *showcase*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * `slices1` field in *showcase*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: showcase.slices1[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<ShowcaseDocumentDataSlices1Slice>;
}

/**
 * showcase document from Prismic
 *
 * - **API ID**: `showcase`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ShowcaseDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ShowcaseDocumentData>,
    "showcase",
    Lang
  >;

/**
 * Content for Twenty for Twenty documents
 */
interface TwentyForTwentyDocumentData {
  /**
   * number field in *Twenty for Twenty*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: twenty_for_twenty.number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  number: prismic.NumberField;

  /**
   * project field in *Twenty for Twenty*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: twenty_for_twenty.project
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;

  /**
   * body field in *Twenty for Twenty*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: twenty_for_twenty.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  body: prismic.KeyTextField;

  /**
   * dates field in *Twenty for Twenty*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: twenty_for_twenty.dates
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  dates: prismic.KeyTextField;

  /**
   * name override field in *Twenty for Twenty*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: twenty_for_twenty.name_override
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name_override: prismic.KeyTextField;

  /**
   * image override field in *Twenty for Twenty*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: twenty_for_twenty.image_override
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_override: prismic.ImageField<never>;

  /**
   * mediums override field in *Twenty for Twenty*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: twenty_for_twenty.mediums_override
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mediums_override: prismic.KeyTextField;

  /**
   * link override field in *Twenty for Twenty*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: twenty_for_twenty.link_override
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_override: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Twenty for Twenty document from Prismic
 *
 * - **API ID**: `twenty_for_twenty`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TwentyForTwentyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TwentyForTwentyDocumentData>,
    "twenty_for_twenty",
    Lang
  >;

export type AllDocumentTypes =
  | LogoSoupDocument
  | PageDocument
  | ProjectDocument
  | ShowcaseDocument
  | TwentyForTwentyDocument;

/**
 * Item in *ContentWidthMedia → Default → Primary → images*
 */
export interface ContentWidthImageSliceDefaultPrimaryImagesItem {
  /**
   * label field in *ContentWidthMedia → Default → Primary → images*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_image.default.primary.images[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * image field in *ContentWidthMedia → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_image.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * vimeoId field in *ContentWidthMedia → Default → Primary → images*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_image.default.primary.images[].vimeoid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vimeoid: prismic.KeyTextField;

  /**
   * loopVideo field in *ContentWidthMedia → Default → Primary → images*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: content_width_image.default.primary.images[].loopvideo
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  loopvideo: prismic.BooleanField;

  /**
   * link field in *ContentWidthMedia → Default → Primary → images*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_image.default.primary.images[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * aspect field in *ContentWidthMedia → Default → Primary → images*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: free
   * - **API ID Path**: content_width_image.default.primary.images[].aspect
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  aspect: prismic.SelectField<
    "free" | "square" | "4/3" | "3/4" | "16/9" | "9/16",
    "filled"
  >;
}

/**
 * Primary content in *ContentWidthMedia → Default → Primary*
 */
export interface ContentWidthImageSliceDefaultPrimary {
  /**
   * label field in *ContentWidthMedia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_image.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * body field in *ContentWidthMedia → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_image.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * width field in *ContentWidthMedia → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: content_width_image.default.primary.isFullContentWidth
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isFullContentWidth: prismic.BooleanField;

  /**
   * background field in *ContentWidthMedia → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: white
   * - **API ID Path**: content_width_image.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<
    "white" | "gray" | "red" | "paper" | "paper-red",
    "filled"
  >;

  /**
   * desktopColumns field in *ContentWidthMedia → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1
   * - **API ID Path**: content_width_image.default.primary.desktopcolumns
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  desktopcolumns: prismic.SelectField<"1" | "2" | "3", "filled">;

  /**
   * animate in field in *ContentWidthMedia → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: content_width_image.default.primary.isAnimated
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isAnimated: prismic.BooleanField;

  /**
   * slice vertical padding field in *ContentWidthMedia → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: content_width_image.default.primary.hasPadding
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hasPadding: prismic.BooleanField;

  /**
   * margin/gaps between images field in *ContentWidthMedia → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: content_width_image.default.primary.hasGap
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hasGap: prismic.BooleanField;

  /**
   * images field in *ContentWidthMedia → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content_width_image.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<ContentWidthImageSliceDefaultPrimaryImagesItem>
  >;

  /**
   * hide field in *ContentWidthMedia → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: content_width_image.default.primary.hide
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hide: prismic.BooleanField;
}

/**
 * Default variation for ContentWidthMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentWidthImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentWidthImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentWidthMedia*
 */
type ContentWidthImageSliceVariation = ContentWidthImageSliceDefault;

/**
 * ContentWidthMedia Shared Slice
 *
 * - **API ID**: `content_width_image`
 * - **Description**: ContentWidthImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentWidthImageSlice = prismic.SharedSlice<
  "content_width_image",
  ContentWidthImageSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * textColor field in *RichText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: dark
   * - **API ID Path**: rich_text.default.primary.textColor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  textColor: prismic.SelectField<"dark" | "white" | "red", "filled">;

  /**
   * backgroundColor field in *RichText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: white
   * - **API ID Path**: rich_text.default.primary.backgroundcolor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundcolor: prismic.SelectField<
    "white" | "gray" | "red" | "paper" | "paper-red",
    "filled"
  >;

  /**
   * width field in *RichText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: full
   * - **API ID Path**: rich_text.default.primary.width
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  width: prismic.SelectField<"full" | "4/5" | "3/5", "filled">;

  /**
   * float field in *RichText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.float
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  float: prismic.SelectField<"center" | "left" | "right">;

  /**
   * padding field in *RichText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: rich_text.default.primary.hasPadding
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hasPadding: prismic.BooleanField;

  /**
   * animate in field in *RichText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: rich_text.default.primary.isAnimated
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isAnimated: prismic.BooleanField;

  /**
   * hide field in *RichText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: rich_text.default.primary.hide
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hide: prismic.BooleanField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *ScreenWidthColumns → Default → Primary → media*
 */
export interface ScreenWidthColumnsSliceDefaultPrimaryMediaItem {
  /**
   * label field in *ScreenWidthColumns → Default → Primary → media*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: screen_width_columns.default.primary.media[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * image field in *ScreenWidthColumns → Default → Primary → media*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: screen_width_columns.default.primary.media[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * vimeoId field in *ScreenWidthColumns → Default → Primary → media*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: screen_width_columns.default.primary.media[].vimeoId
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vimeoId: prismic.KeyTextField;

  /**
   * loopVideo field in *ScreenWidthColumns → Default → Primary → media*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: screen_width_columns.default.primary.media[].loopvideo
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  loopvideo: prismic.BooleanField;

  /**
   * link field in *ScreenWidthColumns → Default → Primary → media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: screen_width_columns.default.primary.media[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * aspect field in *ScreenWidthColumns → Default → Primary → media*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: free
   * - **API ID Path**: screen_width_columns.default.primary.media[].aspect
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  aspect: prismic.SelectField<
    "free" | "square" | "4/3" | "3/4" | "16/9" | "9/16",
    "filled"
  >;
}

/**
 * Primary content in *ScreenWidthColumns → Default → Primary*
 */
export interface ScreenWidthColumnsSliceDefaultPrimary {
  /**
   * background field in *ScreenWidthColumns → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: white
   * - **API ID Path**: screen_width_columns.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<
    "white" | "gray" | "red" | "paper" | "paper-red",
    "filled"
  >;

  /**
   * desktopColumns field in *ScreenWidthColumns → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1
   * - **API ID Path**: screen_width_columns.default.primary.desktopcolumns
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  desktopcolumns: prismic.SelectField<"1" | "2" | "3", "filled">;

  /**
   * slice vertical padding field in *ScreenWidthColumns → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: screen_width_columns.default.primary.hasPadding
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hasPadding: prismic.BooleanField;

  /**
   * animate in field in *ScreenWidthColumns → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: screen_width_columns.default.primary.isAnimated
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isAnimated: prismic.BooleanField;

  /**
   * margin/gaps between images field in *ScreenWidthColumns → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: screen_width_columns.default.primary.hasGap
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hasGap: prismic.BooleanField;

  /**
   * media field in *ScreenWidthColumns → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: screen_width_columns.default.primary.media[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  media: prismic.GroupField<
    Simplify<ScreenWidthColumnsSliceDefaultPrimaryMediaItem>
  >;

  /**
   * hide field in *ScreenWidthColumns → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: screen_width_columns.default.primary.hide
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hide: prismic.BooleanField;
}

/**
 * Default variation for ScreenWidthColumns Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScreenWidthColumnsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScreenWidthColumnsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ScreenWidthColumns*
 */
type ScreenWidthColumnsSliceVariation = ScreenWidthColumnsSliceDefault;

/**
 * ScreenWidthColumns Shared Slice
 *
 * - **API ID**: `screen_width_columns`
 * - **Description**: ScreenWidthColumns
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScreenWidthColumnsSlice = prismic.SharedSlice<
  "screen_width_columns",
  ScreenWidthColumnsSliceVariation
>;

/**
 * Primary content in *ScreenWidthMedia → Default → Primary*
 */
export interface ScreenWidthImageSliceDefaultPrimary {
  /**
   * image field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: screen_width_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * vimeoId field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: screen_width_image.default.primary.vimeoid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vimeoid: prismic.KeyTextField;

  /**
   * loopVideo field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: screen_width_image.default.primary.loopvideo
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  loopvideo: prismic.BooleanField;

  /**
   * slice vertical padding field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: screen_width_image.default.primary.hasPadding
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hasPadding: prismic.BooleanField;

  /**
   * background field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: white
   * - **API ID Path**: screen_width_image.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<
    "white" | "gray" | "red" | "paper" | "paper-red",
    "filled"
  >;

  /**
   * hide field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: screen_width_image.default.primary.hide
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hide: prismic.BooleanField;

  /**
   * aspect field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: free
   * - **API ID Path**: screen_width_image.default.primary.aspect
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  aspect: prismic.SelectField<
    "free" | "square" | "4/3" | "3/4" | "16/9" | "9/16",
    "filled"
  >;
}

/**
 * Default variation for ScreenWidthMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScreenWidthImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScreenWidthImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ScreenWidthMedia*
 */
type ScreenWidthImageSliceVariation = ScreenWidthImageSliceDefault;

/**
 * ScreenWidthMedia Shared Slice
 *
 * - **API ID**: `screen_width_image`
 * - **Description**: ScreenWidthImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScreenWidthImageSlice = prismic.SharedSlice<
  "screen_width_image",
  ScreenWidthImageSliceVariation
>;

/**
 * Item in *Slideshow → Default → Primary → images*
 */
export interface SlideshowSliceDefaultPrimaryImagesItem {
  /**
   * image field in *Slideshow → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slideshow.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Slideshow → Default → Primary*
 */
export interface SlideshowSliceDefaultPrimary {
  /**
   * label field in *Slideshow → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slideshow.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * body field in *Slideshow → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slideshow.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * images field in *Slideshow → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: slideshow.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<SlideshowSliceDefaultPrimaryImagesItem>>;

  /**
   * backgroundColor field in *Slideshow → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: white
   * - **API ID Path**: slideshow.default.primary.backgroundcolor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundcolor: prismic.SelectField<
    "white" | "gray" | "red" | "paper" | "paper-red",
    "filled"
  >;

  /**
   * width field in *Slideshow → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: slideshow.default.primary.isFullContentWidth
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isFullContentWidth: prismic.BooleanField;

  /**
   * hide field in *Slideshow → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: slideshow.default.primary.hide
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hide: prismic.BooleanField;

  /**
   * animate in field in *Slideshow → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: slideshow.default.primary.isAnimated
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isAnimated: prismic.BooleanField;

  /**
   * hasNavDots field in *Slideshow → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: slideshow.default.primary.hasNavDots
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hasNavDots: prismic.BooleanField;
}

/**
 * Default variation for Slideshow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlideshowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SlideshowSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Slideshow*
 */
type SlideshowSliceVariation = SlideshowSliceDefault;

/**
 * Slideshow Shared Slice
 *
 * - **API ID**: `slideshow`
 * - **Description**: Slideshow
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlideshowSlice = prismic.SharedSlice<
  "slideshow",
  SlideshowSliceVariation
>;

/**
 * Primary content in *ValueBlock → Default → Primary*
 */
export interface ValueBlockSliceDefaultPrimary {
  /**
   * eyebrow field in *ValueBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_block.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * title field in *ValueBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * body field in *ValueBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_block.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * drawn Image field in *ValueBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: value_block.default.primary.drawn_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  drawn_image: prismic.ImageField<never>;

  /**
   * hide field in *ValueBlock → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: value_block.default.primary.hide
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hide: prismic.BooleanField;
}

/**
 * Default variation for ValueBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ValueBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ValueBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ValueBlock*
 */
type ValueBlockSliceVariation = ValueBlockSliceDefault;

/**
 * ValueBlock Shared Slice
 *
 * - **API ID**: `value_block`
 * - **Description**: ValueBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ValueBlockSlice = prismic.SharedSlice<
  "value_block",
  ValueBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      LogoSoupDocument,
      LogoSoupDocumentData,
      LogoSoupDocumentDataBrandsItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataSlicesSlice,
      ShowcaseDocument,
      ShowcaseDocumentData,
      ShowcaseDocumentDataProjectsItem,
      ShowcaseDocumentDataSlicesSlice,
      ShowcaseDocumentDataSlices1Slice,
      TwentyForTwentyDocument,
      TwentyForTwentyDocumentData,
      AllDocumentTypes,
      ContentWidthImageSlice,
      ContentWidthImageSliceDefaultPrimaryImagesItem,
      ContentWidthImageSliceDefaultPrimary,
      ContentWidthImageSliceVariation,
      ContentWidthImageSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      ScreenWidthColumnsSlice,
      ScreenWidthColumnsSliceDefaultPrimaryMediaItem,
      ScreenWidthColumnsSliceDefaultPrimary,
      ScreenWidthColumnsSliceVariation,
      ScreenWidthColumnsSliceDefault,
      ScreenWidthImageSlice,
      ScreenWidthImageSliceDefaultPrimary,
      ScreenWidthImageSliceVariation,
      ScreenWidthImageSliceDefault,
      SlideshowSlice,
      SlideshowSliceDefaultPrimaryImagesItem,
      SlideshowSliceDefaultPrimary,
      SlideshowSliceVariation,
      SlideshowSliceDefault,
      ValueBlockSlice,
      ValueBlockSliceDefaultPrimary,
      ValueBlockSliceVariation,
      ValueBlockSliceDefault,
    };
  }
}
